name: TimedMessages
main: name.richardson.james.bukkit.timedmessages.TimedMessages
version: 0.0.1
author: James Richardson (grandwazir)
description: Broadcast messages at specific times.
commands:
  tm:
    description: 'TimedMessages root command'
    alias: [timedmessages]
    usage: '/timedmessages'