name: TimedMessages
description: Broadcast messages at specific times.
version: ${project.version}
author: James Richardson (grandwazir)
website: https://github.com/grandwazir/TimedMessages
main: name.richardson.james.bukkit.timedmessages.TimedMessages

commands:
  tm:
    description: 'TimedMessages root command'
    alias: [timedmessages]
    usage: '/timedmessages'
